# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Routeur.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Router(object):
    def setupUi(self, Router):
        Router.setObjectName("Router")
        Router.resize(510, 520)
        Router.setMaximumSize(QtCore.QSize(510, 520))
        self.centralwidget = QtWidgets.QWidget(Router)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 50, 20))
        self.label.setMaximumSize(QtCore.QSize(50, 20))
        self.label.setObjectName("label")
        self.Renommer = QtWidgets.QLineEdit(self.centralwidget)
        self.Renommer.setGeometry(QtCore.QRect(90, 10, 300, 20))
        self.Renommer.setMaximumSize(QtCore.QSize(300, 20))
        self.Renommer.setObjectName("Renommer")
        self.Renommer_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Renommer_2.setGeometry(QtCore.QRect(410, 10, 80, 20))
        self.Renommer_2.setMaximumSize(QtCore.QSize(80, 20))
        self.Renommer_2.setObjectName("Renommer_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 470, 200))
        self.groupBox.setMaximumSize(QtCore.QSize(470, 200))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(380, 20, 77, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ModifierEth1 = QtWidgets.QPushButton(self.widget)
        self.ModifierEth1.setMaximumSize(QtCore.QSize(80, 20))
        self.ModifierEth1.setObjectName("ModifierEth1")
        self.verticalLayout.addWidget(self.ModifierEth1)
        self.ModifierEth2 = QtWidgets.QPushButton(self.widget)
        self.ModifierEth2.setMaximumSize(QtCore.QSize(80, 20))
        self.ModifierEth2.setObjectName("ModifierEth2")
        self.verticalLayout.addWidget(self.ModifierEth2)
        self.ModifierEth3 = QtWidgets.QPushButton(self.widget)
        self.ModifierEth3.setMaximumSize(QtCore.QSize(80, 20))
        self.ModifierEth3.setObjectName("ModifierEth3")
        self.verticalLayout.addWidget(self.ModifierEth3)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(100, 20, 261, 121))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Ipeth1 = QtWidgets.QLineEdit(self.widget1)
        self.Ipeth1.setMaximumSize(QtCore.QSize(270, 20))
        self.Ipeth1.setObjectName("Ipeth1")
        self.verticalLayout_2.addWidget(self.Ipeth1)
        self.Ipeth2 = QtWidgets.QLineEdit(self.widget1)
        self.Ipeth2.setMaximumSize(QtCore.QSize(270, 20))
        self.Ipeth2.setObjectName("Ipeth2")
        self.verticalLayout_2.addWidget(self.Ipeth2)
        self.Ipeth3 = QtWidgets.QLineEdit(self.widget1)
        self.Ipeth3.setMaximumSize(QtCore.QSize(270, 20))
        self.Ipeth3.setObjectName("Ipeth3")
        self.verticalLayout_2.addWidget(self.Ipeth3)
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 76, 121))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setMaximumSize(QtCore.QSize(75, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setMaximumSize(QtCore.QSize(75, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setMaximumSize(QtCore.QSize(75, 20))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.widget3 = QtWidgets.QWidget(self.groupBox)
        self.widget3.setGeometry(QtCore.QRect(40, 150, 381, 48))
        self.widget3.setObjectName("widget3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ActiverEth1 = QtWidgets.QPushButton(self.widget3)
        self.ActiverEth1.setMaximumSize(QtCore.QSize(80, 20))
        self.ActiverEth1.setObjectName("ActiverEth1")
        self.gridLayout.addWidget(self.ActiverEth1, 0, 0, 1, 1)
        self.ActiverEth2 = QtWidgets.QPushButton(self.widget3)
        self.ActiverEth2.setMaximumSize(QtCore.QSize(80, 20))
        self.ActiverEth2.setObjectName("ActiverEth2")
        self.gridLayout.addWidget(self.ActiverEth2, 0, 1, 1, 1)
        self.ActiverEth3 = QtWidgets.QPushButton(self.widget3)
        self.ActiverEth3.setMaximumSize(QtCore.QSize(80, 20))
        self.ActiverEth3.setObjectName("ActiverEth3")
        self.gridLayout.addWidget(self.ActiverEth3, 0, 2, 1, 1)
        self.DesactiverEth1 = QtWidgets.QPushButton(self.widget3)
        self.DesactiverEth1.setMaximumSize(QtCore.QSize(90, 20))
        self.DesactiverEth1.setObjectName("DesactiverEth1")
        self.gridLayout.addWidget(self.DesactiverEth1, 1, 0, 1, 1)
        self.DesactiverEth2 = QtWidgets.QPushButton(self.widget3)
        self.DesactiverEth2.setMaximumSize(QtCore.QSize(90, 20))
        self.DesactiverEth2.setObjectName("DesactiverEth2")
        self.gridLayout.addWidget(self.DesactiverEth2, 1, 1, 1, 1)
        self.ModifierEth1_9 = QtWidgets.QPushButton(self.widget3)
        self.ModifierEth1_9.setMaximumSize(QtCore.QSize(90, 20))
        self.ModifierEth1_9.setObjectName("ModifierEth1_9")
        self.gridLayout.addWidget(self.ModifierEth1_9, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 260, 470, 120))
        self.groupBox_2.setMaximumSize(QtCore.QSize(470, 120))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget4 = QtWidgets.QWidget(self.groupBox_2)
        self.widget4.setGeometry(QtCore.QRect(60, 20, 90, 61))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget4)
        self.label_5.setMaximumSize(QtCore.QSize(90, 20))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget4)
        self.label_6.setMaximumSize(QtCore.QSize(75, 20))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.widget5 = QtWidgets.QWidget(self.groupBox_2)
        self.widget5.setGeometry(QtCore.QRect(160, 20, 281, 61))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Iproute = QtWidgets.QLineEdit(self.widget5)
        self.Iproute.setMaximumSize(QtCore.QSize(270, 20))
        self.Iproute.setObjectName("Iproute")
        self.verticalLayout_5.addWidget(self.Iproute)
        self.Via = QtWidgets.QLineEdit(self.widget5)
        self.Via.setMaximumSize(QtCore.QSize(270, 20))
        self.Via.setObjectName("Via")
        self.verticalLayout_5.addWidget(self.Via)
        self.widget6 = QtWidgets.QWidget(self.groupBox_2)
        self.widget6.setGeometry(QtCore.QRect(10, 90, 451, 22))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AjtRoute = QtWidgets.QPushButton(self.widget6)
        self.AjtRoute.setMaximumSize(QtCore.QSize(110, 20))
        self.AjtRoute.setObjectName("AjtRoute")
        self.horizontalLayout.addWidget(self.AjtRoute)
        self.SupprRoute = QtWidgets.QPushButton(self.widget6)
        self.SupprRoute.setMaximumSize(QtCore.QSize(110, 20))
        self.SupprRoute.setObjectName("SupprRoute")
        self.horizontalLayout.addWidget(self.SupprRoute)
        self.widget7 = QtWidgets.QWidget(self.centralwidget)
        self.widget7.setGeometry(QtCore.QRect(60, 430, 381, 41))
        self.widget7.setObjectName("widget7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ActRoutage = QtWidgets.QPushButton(self.widget7)
        self.ActRoutage.setMaximumSize(QtCore.QSize(110, 30))
        self.ActRoutage.setObjectName("ActRoutage")
        self.horizontalLayout_2.addWidget(self.ActRoutage)
        self.DesactRoutage = QtWidgets.QPushButton(self.widget7)
        self.DesactRoutage.setMaximumSize(QtCore.QSize(115, 30))
        self.DesactRoutage.setObjectName("DesactRoutage")
        self.horizontalLayout_2.addWidget(self.DesactRoutage)
        self.DesactRoutage_2 = QtWidgets.QPushButton(self.widget7)
        self.DesactRoutage_2.setMaximumSize(QtCore.QSize(110, 30))
        self.DesactRoutage_2.setObjectName("DesactRoutage_2")
        self.horizontalLayout_2.addWidget(self.DesactRoutage_2)
        self.widget8 = QtWidgets.QWidget(self.centralwidget)
        self.widget8.setGeometry(QtCore.QRect(60, 390, 381, 31))
        self.widget8.setObjectName("widget8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.InfoRouteur = QtWidgets.QPushButton(self.widget8)
        self.InfoRouteur.setMaximumSize(QtCore.QSize(130, 30))
        self.InfoRouteur.setObjectName("InfoRouteur")
        self.horizontalLayout_3.addWidget(self.InfoRouteur)
        self.RoutTable = QtWidgets.QPushButton(self.widget8)
        self.RoutTable.setMaximumSize(QtCore.QSize(130, 30))
        self.RoutTable.setObjectName("RoutTable")
        self.horizontalLayout_3.addWidget(self.RoutTable)
        Router.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Router)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        Router.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Router)
        self.statusbar.setObjectName("statusbar")
        Router.setStatusBar(self.statusbar)
        self.actionEnregistrer = QtWidgets.QAction(Router)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionOuvrir = QtWidgets.QAction(Router)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addAction(self.actionOuvrir)
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(Router)
        QtCore.QMetaObject.connectSlotsByName(Router)

    def retranslateUi(self, Router):
        _translate = QtCore.QCoreApplication.translate
        Router.setWindowTitle(_translate("Router", "Router"))
        self.label.setText(_translate("Router", "<html><head/><body><p align=\"center\">Nom</p></body></html>"))
        self.Renommer_2.setToolTip(_translate("Router", "<html><head/><body><p>Renommez le nom du router</p></body></html>"))
        self.Renommer_2.setText(_translate("Router", "Renommer"))
        self.groupBox.setTitle(_translate("Router", "Configuration des interfaces"))
        self.ModifierEth1.setToolTip(_translate("Router", "<html><head/><body><p>Valider le changement d\'adresse IP pour Eth1</p></body></html>"))
        self.ModifierEth1.setText(_translate("Router", "Modifier IP"))
        self.ModifierEth2.setToolTip(_translate("Router", "<html><head/><body><p>Valider le changement d\'adresse IP pour Eth2</p></body></html>"))
        self.ModifierEth2.setText(_translate("Router", "Modifier IP"))
        self.ModifierEth3.setToolTip(_translate("Router", "<html><head/><body><p>Valider le changement d\'adresse IP pour Eth3</p></body></html>"))
        self.ModifierEth3.setText(_translate("Router", "Modifier IP"))
        self.label_2.setText(_translate("Router", "<html><head/><body><p align=\"center\">Eth1 ( IP/Mask)</p></body></html>"))
        self.label_3.setText(_translate("Router", "<html><head/><body><p align=\"center\">Eth2 ( IP/Mask)</p></body></html>"))
        self.label_4.setText(_translate("Router", "<html><head/><body><p align=\"center\">Eth3 ( IP/Mask)</p></body></html>"))
        self.ActiverEth1.setToolTip(_translate("Router", "<html><head/><body><p>Active l\'interface Eth1</p></body></html>"))
        self.ActiverEth1.setText(_translate("Router", "Activer Eth1"))
        self.ActiverEth2.setToolTip(_translate("Router", "<html><head/><body><p>Active l\'interface Eth2</p></body></html>"))
        self.ActiverEth2.setText(_translate("Router", "Activer Eth2"))
        self.ActiverEth3.setToolTip(_translate("Router", "<html><head/><body><p>Active l\'interface Eth3</p></body></html>"))
        self.ActiverEth3.setText(_translate("Router", "Activer Eth3"))
        self.DesactiverEth1.setToolTip(_translate("Router", "<html><head/><body><p>désactive l\'interface Eth1</p></body></html>"))
        self.DesactiverEth1.setText(_translate("Router", "Desactiver Eth1"))
        self.DesactiverEth2.setToolTip(_translate("Router", "<html><head/><body><p>désactive l\'interface Eth2</p></body></html>"))
        self.DesactiverEth2.setText(_translate("Router", "Desactiver Eth2"))
        self.ModifierEth1_9.setToolTip(_translate("Router", "<html><head/><body><p>désactive l\'interface Eth3</p></body></html>"))
        self.ModifierEth1_9.setText(_translate("Router", "Desactiver Eth3"))
        self.groupBox_2.setTitle(_translate("Router", "Options de routage"))
        self.label_5.setText(_translate("Router", "<html><head/><body><p align=\"center\">Réseau ( IP/Mask)</p></body></html>"))
        self.label_6.setText(_translate("Router", "<html><head/><body><p align=\"center\">Via (EthX)</p></body></html>"))
        self.AjtRoute.setToolTip(_translate("Router", "<html><head/><body><p>Ajoute la route défini ci-dessu</p></body></html>"))
        self.AjtRoute.setText(_translate("Router", "Ajouter la route"))
        self.SupprRoute.setToolTip(_translate("Router", "<html><head/><body><p>Supprime la route défini ci-dessu</p></body></html>"))
        self.SupprRoute.setText(_translate("Router", "Supprimer la route"))
        self.ActRoutage.setToolTip(_translate("Router", "<html><head/><body><p>Active le routage </p></body></html>"))
        self.ActRoutage.setText(_translate("Router", "Activer le routage"))
        self.DesactRoutage.setToolTip(_translate("Router", "<html><head/><body><p>Désactive le routage</p></body></html>"))
        self.DesactRoutage.setText(_translate("Router", "Désactiver le routage"))
        self.DesactRoutage_2.setToolTip(_translate("Router", "<html><head/><body><p>Quitte la configuration du routeur</p></body></html>"))
        self.DesactRoutage_2.setText(_translate("Router", "Quitter"))
        self.InfoRouteur.setToolTip(_translate("Router", "<html><head/><body><p>Affiche les informations du routeur</p></body></html>"))
        self.InfoRouteur.setText(_translate("Router", "Informations du routeur"))
        self.RoutTable.setToolTip(_translate("Router", "<html><head/><body><p>Affiche la table de routage</p></body></html>"))
        self.RoutTable.setText(_translate("Router", "Table de routage"))
        self.menuFichier.setTitle(_translate("Router", "Fichier"))
        self.actionEnregistrer.setText(_translate("Router", "Enregistrer"))
        self.actionOuvrir.setText(_translate("Router", "Ouvrir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Router = QtWidgets.QMainWindow()
    ui = Ui_Router()
    ui.setupUi(Router)
    Router.show()
    sys.exit(app.exec_())

